spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flights
    username: root
    password: carm2394
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false

